#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the GNU
# General Public License, v.3.0. If a copy of the GPL was not distributed with this
# file, You can obtain one at https://www.gnu.org/licenses/gpl-3.0.en.html.

from telethon.sync import TelegramClient
from telethon.sessions import StringSession

print("""\nWelcome to TufaanBot Session tool made by @AkHiL_SI. 
    Join @TufaanBot_Support for any query !""")

print("an online String Session generator tool for telethon.")

print("""
 Get API id and hash from 
  my.telegram.org and fill real values to proceed...""")
APP_ID = int(input("Enter APP ID here: "))
API_HASH = input("Enter API HASH here: ")

with TelegramClient(StringSession(), APP_ID, API_HASH) as client:
    session_str = client.session.save()
    s_m = client.send_message("me", session_str)
    s_m.reply(
        "➣Above is the string session for your TufaanBot Telethon session generated by [TUFAANBOT](https://t.me/TheTufaanBot).... For any query, join @TufaanBot_Support "
    )

print(
    "You have successfully generated  your   TufaanBot String Session... Check ur  saved message...ab ja gaand mara... "
)
